In [2]:
import pandas as pd

In [3]:
so_surv_df = pd.read_csv('Nato/nato.csv')
so_surv_df

##df - dataframe

,organisation,year,vendor_country,vendor_name,amount,description,country_code,Type,Period
0,NATO,2008,Belgium,INFRAVISION BVBA,1.259084e+06,SOFTWARE LICENCES AND PRODUCT MAINTENANCE,BEL,Orders Awarded,Q3Q4
1,NATO,2008,Belgium,THALES BELGIUM SA,1.830885e+06,SUPPLIES FOR AWACS,BEL,Orders Awarded,Q3Q4
2,NATO,2008,Belgium,THALES BELGIUM SA,1.694785e+08,48 PROTECTED VEHICLE PLATFORMS (DINGO II) INTE...,BEL,Orders Awarded,Q1Q2
3,NATO,2008,Belgium,THALES BELGIUM SA,1.694785e+08,"48 PROTECTED VEHICLE PLATFORMS (DINGO II), INT...",BEL,Orders Awarded,Q1Q2
4,NATO,2008,Bulgaria,VMZ CO,2.180010e+06,SUPPLY OF AMMUNITION - 40 MM ROUNDS,BGR,Orders Awarded,Q1Q2
...,...,...,...,...,...,...,...,...,...
7197,NATO,2019,United States,TRIMBLE MILITARY AND ADVANCED,1.592282e+05,PROVISION OF TRIMBLE FORCE 27 GPS RECEIVER,USA,Orders Awarded,Q3Q4
7198,NATO,2019,United States,US DYNAMICS CORPORATION,4.179246e+05,SPARE PARTS FOR THE SUPPORT OF ANFPS 117 RADAR...,USA,Orders Awarded,Q1Q2
7199,NATO,2019,United States,VAREC INC,1.388800e+07,PROVISION NATO FUEL MONITORING SERV- AUG-DEC -...,USA,Outline Agreement,Q3Q4
7200,NATO,2019,United States,WESCO MANUFACTURING INC,1.813427e+06,INSPECTION REPAIR AND OVERHAUL OF VARIOUS C-1...,USA,Outline Agreement,Q1Q2
7201,NATO,2019,United States,WESCO MANUFACTURING INC,1.876464e+06,INSPECTION REPAIR AND OVERHAUL OF VARIOUS C-1...,USA,Outline Agreement,Q1Q2

In [4]:
so_surv_df.shape

(7202, 9)

In [5]:
so_surv_df.columns

Index(['organisation', 'year', 'vendor_country', 'vendor_name', 'amount',
       'description', 'country_code', 'Type', 'Period'],
      dtype='object')

In [6]:
so_surv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7202 entries, 0 to 7201
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   organisation    7202 non-null   object
 1   year            7202 non-null   int64
 2   vendor_country  7202 non-null   object
 3   vendor_name     7202 non-null   object
 4   amount          7202 non-null   float64
 5   description     7202 non-null   object
 6   country_code    7202 non-null   object
 7   Type            7202 non-null   object
 8   Period          7202 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 506.5+ KB